server:
  port: 8080

spring:
  application:
    name: my-vault-client
    vault-path: myapp/

  cloud:
    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: my-root-token
      kv:
        enabled: true
        backend: secret
        default-context: application